### ISSUE TITLE
ValueError: could not convert string to float: '7.1-8'

### ISSUE THREAD

**Issue by technoluc** [RaSerge/ansible-proxmox-inventory#2]
Hi! Thanks for your hard work, but unfortunately I can't get it working. 

`python3 proxmox.py --list --pretty`
 
This is the outcome:

```Traceback (most recent call last):
  File "/home/aceventura/private/provisioning-proxmox/ansible-proxmox-inventory/proxmox.py", line 316, in <module>
    main()
  File "/home/aceventura/private/provisioning-proxmox/ansible-proxmox-inventory/proxmox.py", line 301, in main
    data = main_list(options, config_path)
  File "/home/aceventura/private/provisioning-proxmox/ansible-proxmox-inventory/proxmox.py", line 190, in main_list
    qemu_list = proxmox_api.node_qemu(node)
  File "/home/aceventura/private/provisioning-proxmox/ansible-proxmox-inventory/proxmox.py", line 154, in node_qemu
    return self.vms_by_type(node, 'qemu')
  File "/home/aceventura/private/provisioning-proxmox/ansible-proxmox-inventory/proxmox.py", line 148, in vms_by_type
    return ProxmoxVMList(self.get('api2/json/nodes/{0}/{1}'.format(node, type)), self.version().get_version())
  File "/home/aceventura/private/provisioning-proxmox/ansible-proxmox-inventory/proxmox.py", line 65, in get_version
    return float(self['version'])
ValueError: could not convert string to float: '7.1-8'
```

Am I missing something?

**Comment by SalehAlolayan** [comment]
dirty work around hardcode your ver in the code 

class ProxmoxVersion(dict):
    def get_version(self):
        return float(x.x)
